# Generated by Django 5.2.1 on 2025-05-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roomreservation",
            unique_together=set(),
        ),
    ]
