# Generated by Django 5.2.1 on 2025-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_readinglistlike_savedreadinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookborrowing",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
