# Generated by Django 5.2.1 on 2025-05-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_bookborrowing_due_date"),
    ]

    operations = []
